package us.martink.mybatis.dao;

import org.mybatis.cdi.Mapper;
import us.martink.mybatis.entities.Course;

import java.util.List;

@Mapper
public interface CourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psk_1.course
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psk_1.course
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    int insert(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psk_1.course
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    Course selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psk_1.course
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    List<Course> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psk_1.course
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    int updateByPrimaryKey(Course record);
}