package us.martink.mybatis.dao;

import org.mybatis.cdi.Mapper;
import us.martink.mybatis.entities.Student;

import java.util.List;

@Mapper
public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psk_1.student
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psk_1.student
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psk_1.student
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    Student selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psk_1.student
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    List<Student> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psk_1.student
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    int updateByPrimaryKey(Student record);
}