package us.martink.mybatis.dao;

import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;
import us.martink.mybatis.entities.StudentCourse;

import java.util.List;

@Mapper
public interface StudentCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psk_1.student_course
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    int deleteByPrimaryKey(@Param("studentId") Integer studentId, @Param("courseId") Integer courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psk_1.student_course
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    int insert(StudentCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psk_1.student_course
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    List<StudentCourse> selectAll();
}