package us.martink.mybatis.dao;

import org.mybatis.cdi.Mapper;
import us.martink.mybatis.entities.University;

import java.util.List;

@Mapper
public interface UniversityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psk_1.university
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psk_1.university
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    int insert(University record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psk_1.university
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    University selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psk_1.university
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    List<University> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psk_1.university
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    int updateByPrimaryKey(University record);
}