package us.martink.mybatis.entities;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psk_1.course.id
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psk_1.course.name
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psk_1.course.id
     *
     * @return the value of psk_1.course.id
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psk_1.course.id
     *
     * @param id the value for psk_1.course.id
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psk_1.course.name
     *
     * @return the value of psk_1.course.name
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psk_1.course.name
     *
     * @param name the value for psk_1.course.name
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    public void setName(String name) {
        this.name = name;
    }
}