package us.martink.mybatis.entities;

import java.util.List;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psk_1.student.id
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psk_1.student.first_name
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psk_1.student.last_name
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psk_1.student.registration_no
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    private String registrationNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psk_1.student.university_id
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    private Integer universityId;

    private University university;
    private List<Course> courses;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psk_1.student.id
     *
     * @return the value of psk_1.student.id
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psk_1.student.id
     *
     * @param id the value for psk_1.student.id
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psk_1.student.first_name
     *
     * @return the value of psk_1.student.first_name
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psk_1.student.first_name
     *
     * @param firstName the value for psk_1.student.first_name
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psk_1.student.last_name
     *
     * @return the value of psk_1.student.last_name
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psk_1.student.last_name
     *
     * @param lastName the value for psk_1.student.last_name
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psk_1.student.registration_no
     *
     * @return the value of psk_1.student.registration_no
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    public String getRegistrationNo() {
        return registrationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psk_1.student.registration_no
     *
     * @param registrationNo the value for psk_1.student.registration_no
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    public void setRegistrationNo(String registrationNo) {
        this.registrationNo = registrationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psk_1.student.university_id
     *
     * @return the value of psk_1.student.university_id
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    public Integer getUniversityId() {
        return universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psk_1.student.university_id
     *
     * @param universityId the value for psk_1.student.university_id
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    public void setUniversityId(Integer universityId) {
        this.universityId = universityId;
    }

    public University getUniversity() {
        return university;
    }

    public void setUniversity(University university) {
        this.university = university;
    }

    public List<Course> getCourses() {
        return courses;
    }

    public void setCourses(List<Course> courses) {
        this.courses = courses;
    }
}