package us.martink.mybatis.entities;

public class University {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psk_1.university.id
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psk_1.university.title
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psk_1.university.id
     *
     * @return the value of psk_1.university.id
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psk_1.university.id
     *
     * @param id the value for psk_1.university.id
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psk_1.university.title
     *
     * @return the value of psk_1.university.title
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psk_1.university.title
     *
     * @param title the value for psk_1.university.title
     *
     * @mbg.generated Tue Mar 21 23:31:39 EET 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }
}